---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
script: bundle exec rake release_checks
matrix:
  fast_finish: true
  include:
  - rvm: 2.4
    env: PUPPET_VERSION="~> 5.0" FACTER_letsencrypt_nginx_firstrun=""
  - rvm: 2.4
    env: PUPPET_VERSION="~> 5.0"
